angular.module('namesApp', [])
.directive('splitArray', function() {
    return {
        restrict: 'A',
        require: 'ngModel',
        link: function(scope, element, attr, ngModel) {

            function fromUser(text) {
                return text.split("\n");
            }

            function toUser(array) {
                return array.join("\n");
            }

            ngModel.$parsers.push(fromUser);
            ngModel.$formatters.push(toUser);
        }
    };
})
.controller('namesController', function(){
    var nameCtrl = this;
    nameCtrl.project = "";

    
    nameCtrl.adjectives = [
      /*Colors*/
      "black",
      "blue",
      "brown",
      "clear",
      "crimson",
      "cyan",
      "golden",
      "green",
      "gray",
      "indigo",
      "ivory",
      "khaki",
      "lemon",
      "magenta",
      "maroon",
      "navy",
      "ochre",
      "olive",
      "orange",
      "peach",
      "pink",
      "purple",
      "rainbow",
      "red",
      "rose",
      "scarlet",
      "sienna",
      "teal",
      "umber",
      "white",
      "yellow",
      /*temperatures*/
      "chilly",
      "cold",
      "cooling",
      "fiery",
      "freezing",
      "frozen",
      "heating",
      "hot",
      "icy",
      "melting",
      "tepid",
      "warmo",
      /*surfaces*/
      "gritty",
      "rough",
      "shiny",
      "matte",
      "slick",
      "bright",
      "dark",
      "smooth",
      "bumpy",
      "spiky",
      "wet",
      "dry",
      "damp",
      /*time*/
      "ancient",
      "modern",
      "early",
      "fast",
      "fresh",
      "quick",
      "new",
      "young",
      "swift",
      /*sound*/
      "quiet",
      "loud",
      "silent",
      "noisy",
      /*mental*/
      "busy",
      "brave",
      "bold",
      "calm",
      "clean",
      "clever",
      "civil",
      "careful",
      "committed",
      "confident",
      "capable",
      "cheerful",
      "cogent",
      "celestial",
      "composed",
      "daring",
      "deft",
      "eager",
      "earnest",
      "exact",
      "great",
      "grand",
      "gutsy",
      "graceful",
      "hale",
      "hardy",
      "intense",
      "joyful",
      "joyous",
      "jaunty",
      "just",
      "keen",
      "lucid",
      "noble",
      "nimble",
      "precise",
      "regal",
    ]
    nameCtrl.nouns = [

/*metals*/
"Aluminium ",
"Barium ",
"Beryllium ",
"Bismuth ",
"Cadmium ",
"Calcium ",
"Cesium ",
"Chromium ",
"Cobalt ",
"Copper ",
"Gallium ",
"Gold ",
"Iron ",
"Lead ",
"Lithium ",
"Magnesium ",
"Mercury",
"Nickel  ",
"Platinum ",
"Plutonium ",
"Potassium  ",
"Radium  ",
"Silver ",
"Sodium  ",
"Tin ",
"Titanium ",
"Tungsten ",
"Uranium ",
"Zinc ",
"Zirconium",
/*Alloys*/
"Brass",
"Electrum",
"Solder",
"Steel",
"Wootz",

/* Birds*/
"Argus",
"Barbet",
"Crake",
"Crane",
"Duck",
"Eagle",
"Egret",
"Emu",
"Falcon",
"Gannet",
"Goose",
"Gull",
"Hawk",
"Heron",
"Ibis",
"Kestrel",
"Kite",
"Kiwi",
"Magpie",
"Osprey",
"Ostrich",
"Owl",
"Pelican",
"Penguin",
"Petrel",
"Pheasant",
"Plover",
"Quail",
"Stork",
"Swift",
"Tern",
"Partridge",
"Oriole",
"Monarch",
"Jay",
"Robin",
"Lark",
"Wren",
/*Gems and Stones*/
"Ruby",
"Diamond",
"Beryl",
"Quartz",
"Emerald",
"Agate",
"Topaz",
"Zircon",
"Opal",
"Onyx",
"Garnet",
"Amber",
"Pearl",
"Sapphire",
"Jade",
"Jet",
"Coral",
"Flint",
"Marble",
"Chalk",
"Glass",
"Basalt",
"Granite",
"Clay",
"Sand",
"Gneiss",

    ];
    nameCtrl.newProject = function(){
      nameCtrl.project = nameCtrl.adjectives[Math.floor(Math.random() * nameCtrl.adjectives.length)] + " " + nameCtrl.nouns[Math.floor(Math.random() * nameCtrl.nouns.length)]
    };
    nameCtrl.newProject();

});
